### ISSUE TITLE
Bekomme alle Daten, aber irgendwas scheint nich zu stimmen.

### ISSUE THREAD

**Issue by ecoone-2020** [volkerrichert/ioBroker.ecotouch#2]
Hallo, Ich habe 8 Wärmepumpe von Waterkotte die ich für uns betreue, ich bekomme auch alle Daten, aber irgendwas schein der Code nicht zu mögen.

Hier der Log auszug

javascript.0 | 2020-10-27 12:41:00.118 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
-- | -- | -- | --
javascript.0 | 2020-10-27 12:41:00.118 | error | at endReadableNT (_stream_readable.js:1223:12)
javascript.0 | 2020-10-27 12:41:00.118 | error | at IncomingMessage.EventEmitter.emit (domain.js:483:12)
javascript.0 | 2020-10-27 12:41:00.118 | error | at IncomingMessage.emit (events.js:326:22)
javascript.0 | 2020-10-27 12:41:00.118 | error | at Object.onceWrapper (events.js:420:28)
javascript.0 | 2020-10-27 12:41:00.118 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:1076:12)
javascript.0 | 2020-10-27 12:41:00.118 | error | at Request.EventEmitter.emit (domain.js:483:12)
javascript.0 | 2020-10-27 12:41:00.118 | error | at Request.emit (events.js:314:20)
javascript.0 | 2020-10-27 12:41:00.118 | error | at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:1154:10)
javascript.0 | 2020-10-27 12:41:00.118 | error | at Request.EventEmitter.emit (domain.js:483:12)
javascript.0 | 2020-10-27 12:41:00.118 | error | at Request.emit (events.js:314:20)
javascript.0 | 2020-10-27 12:41:00.118 | error | at Request.self.callback (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:185:22)
javascript.0 | 2020-10-27 12:41:00.118 | error | at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request-promise-core/lib/plumbing.js:46:31)
javascript.0 | 2020-10-27 12:41:00.118 | error | at Request.plumbing.callback (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request-promise-core/lib/plumbing.js:104:33)
javascript.0 | 2020-10-27 12:41:00.118 | error | at new StatusCodeError (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request-promise-core/lib/errors.js:32:15)
javascript.0 | 2020-10-27 12:41:00.118 | error | (13810) StatusCodeError: 500 - "#E_RE-LOGIN_ATTEMPT\n"
javascript.0 | 2020-10-27 12:41:00.118 | error | (13810) Error: 500 - "#E_RE-LOGIN_ATTEMPT\n"
javascript.0 | 2020-10-27 12:41:00.118 | error | (13810) An error happened which is most likely from one of your scripts, but the originating script could not be detected.

**Comment by volkerrichert** [comment]
Hm, an sich ist das RE-Login nicht relevant. Wie werden denn die 8 Stück abgefragt? Vielleicht dauert das auch zu lange und der Request ist zu früh wieder da. 

Verscuh mal /5 statt /1 bei 
`else schedule("*/1 * * * *", run)`
am Ende
